// <auto-generated />
using System;
using DMO.Alpha.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMO.Alpha.Infrastructure.Migrations
{
    [DbContext(typeof(DmoDbContext))]
    partial class DmoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMO.Alpha.Core.Boquilhas.BqMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BqRepairTraceId")
                        .HasColumnType("integer");

                    b.Property<int?>("Discrepancy")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BqRepairTraceId");

                    b.ToTable("BqMovements");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Boquilhas.BqRepairTrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BqContextId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BqContextId")
                        .IsUnique();

                    b.HasIndex("ToolId");

                    b.ToTable("BqRepairTraces");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Identity.AdminAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssociatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminAssociations");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStandBy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.BqContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobOnId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobOnId")
                        .IsUnique();

                    b.ToTable("BqContexts");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.CmContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobOnId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobOnId")
                        .IsUnique();

                    b.ToTable("CmContexts");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.JobOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionNumber")
                        .IsUnique();

                    b.ToTable("JobOns");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.MfContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobOnId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobOnId")
                        .IsUnique();

                    b.ToTable("MfContexts");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Tools.Tool", b =>
                {
                    b.Property<string>("ToolId")
                        .HasColumnType("text");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ToolId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Boquilhas.BqMovement", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Boquilhas.BqRepairTrace", "Trace")
                        .WithMany()
                        .HasForeignKey("BqRepairTraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Boquilhas.BqRepairTrace", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Production.BqContext", "BqContext")
                        .WithMany()
                        .HasForeignKey("BqContextId");

                    b.HasOne("DMO.Alpha.Core.Tools.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BqContext");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.BqContext", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Production.JobOn", "JobOn")
                        .WithOne("BqContext")
                        .HasForeignKey("DMO.Alpha.Core.Production.BqContext", "JobOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOn");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.CmContext", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Production.JobOn", "JobOn")
                        .WithOne("CmContext")
                        .HasForeignKey("DMO.Alpha.Core.Production.CmContext", "JobOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOn");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.JobOn", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Production.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.MfContext", b =>
                {
                    b.HasOne("DMO.Alpha.Core.Production.JobOn", "JobOn")
                        .WithOne("MfContext")
                        .HasForeignKey("DMO.Alpha.Core.Production.MfContext", "JobOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOn");
                });

            modelBuilder.Entity("DMO.Alpha.Core.Production.JobOn", b =>
                {
                    b.Navigation("BqContext");

                    b.Navigation("CmContext");

                    b.Navigation("MfContext");
                });
#pragma warning restore 612, 618
        }
    }
}
